# Makefile
 
# CC=clang -fsanitize=address
# CC=gcc -fsanitize=address
CC=gcc
CPPFLAGS=
CFLAGS= -Wall -Wextra -std=c99 -O0 -g3 -fdiagnostics-color=auto
LDFLAGS=
LDLIBS=
XFILES = worker
EXEC = binFunc
TESTS = 
all: binFunc

worker:

task_mgr:

 
clean:
	rm -f *.o
	$(RM) $(EXEC) 
# END
